kieker-analysis/build.gradle
kieker-analysis/src/kieker/analysis/plugin/reader/AbstractStringRegistryReaderPlugin.java
kieker-analysis/src/kieker/analysis/plugin/reader/RegistryRecordHandler.java
kieker-analysis/src/kieker/analysis/plugin/reader/RegularRecordHandler.java
kieker-analysis/src/kieker/analysis/plugin/reader/StringRegistryCache.java
kieker-analysis/src/kieker/analysis/plugin/reader/amqp/AMQPReader.java
kieker-common/src/kieker/common/util/registry/IRegistry.java
kieker-common/src/kieker/common/util/registry/Lookup.java
kieker-common/src/kieker/common/util/registry/Registry.java
kieker-common/src/kieker/common/util/registry/RegistryUtil.java
kieker-common/src/kieker/common/util/registry/reader/GetValueAdapter.java
kieker-monitoring/src/kieker/monitoring/writer/amqp/AMQPWriter.java

As already commented in pull request #26 changing the base branch did not trigger the pipeline. Therefor this is a fresh PR towards the correct branch ('master').

Issue 1468 amqp concurrent

---

kieker-monitoring/src/kieker/monitoring/writer/amqp/AMQPWriter.java

Fixed the CS warning that caused the build to become unstable.

Fixed CS warning

---

kieker-analysis/src/kieker/analysisteetime/plugin/filter/forward/CountingFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/forward/TestCountingFilter.java

Test if the planned workflow (create subtask from 1471 for stage to be migrated in JIRA -> create branch with subtask id, issue-1477 in this case -> migrate on this branch -> create pull request to 1471-analysis-teetime-migration -> pull migrated stage into 1471-analysis-teetime-migration) works.

migration of CountingFilter

---

bin/dev/snap-ci/master/1-compile.sh
bin/dev/snap-ci/master/2-unit-test.sh
bin/dev/snap-ci/master/3-static-analysis.sh
bin/dev/snap-ci/master/4-release-check-short.sh
bin/dev/snap-ci/master/5-release-check-extended.sh
gradle.properties
kieker-tools/src/kieker/tools/opad/timeseries/forecast/ForecastObjectives.java
kieker-tools/src/kieker/tools/opad/timeseries/forecast/naive/NaiveForecaster.java

- Changed Java environment from OpenJDK 6 to OpenJDK 7.
- Fixed some unmappable characters that made the build fail under OpenJDK 7.
These changes should fix the certificate issues experienced with OpenJDK 6.

Kieker 1482 cert issues

---

config/fb-filter.xml
kieker-analysis/src/kieker/analysisteetime/plugin/filter/forward/AnalysisThroughputFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/forward/StringBufferFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/forward/TeeFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/record/MonitoringThroughputFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/record/delayfilter/RealtimeRecordDelayFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/record/delayfilter/components/RealtimeRecordDelayConsumer.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/record/delayfilter/components/RealtimeRecordDelayProducer.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/select/timestampfilter/TimestampFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/select/timestampfilter/components/AbstractTimestampFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/select/traceidfilter/TraceIdFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/sink/CPUUtilizationDisplayFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/sink/GCDisplayFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/filter/sink/MethodAndComponentFlowDisplayFilter.java
kieker-analysis/src/kieker/analysisteetime/plugin/reader/AbstractReader.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/forward/TestCountingFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/forward/TestStringBufferFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/forward/TestTeeFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/record/TestMonitoringThroughputFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/select/TestTimestampFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/select/TestTraceIdFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/select/TestTypeFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/sink/TestCPUUtilizationDisplayFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/sink/TestGCDisplayFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/sink/TestMemSwapUtilizationDisplayFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/sink/TestMethodAndComponentFlowDisplayFilter.java
kieker-analysis/test/kieker/test/analysisteetime/junit/plugin/filter/sink/TestThreadsStatusDisplayFilter.java
kieker-tools/src/kieker/toolsteetime/logReplayer/AbstractLogReplayer.java
kieker-tools/src/kieker/toolsteetime/logReplayer/JMSLogReplayer.java
kieker-tools/src/kieker/toolsteetime/logReplayer/LogReplayerConfiguration.java

Pull request for findbugs, checkstyle, and pmd fixes on imported, already migrated stages

Issue 1481 import of already migrated analysis filters

---

kieker-monitoring/test/kieker/test/monitoring/junit/probe/spring/executions/jetty/bookstore/Catalog.java
kieker-monitoring/test/kieker/test/monitoring/junit/writer/collector/TestRawDataStorage.java
kieker-monitoring/test/kieker/test/monitoring/junit/writer/collector/TestRawDataWriter.java
kieker-tools/src/kieker/tools/bridge/connector/ServiceConnectorFactory.java

In this branch I try to further reduce the alerts by checkstyle, findbugs and pmd.

Code Quality fixes.

---

kieker-common/src/kieker/common/exception/InvalidConfigurationException.java
kieker-monitoring/src/kieker/monitoring/core/controller/WriterController.java
kieker-tools/src/kieker/tools/bridge/connector/ServiceConnectorFactory.java

Further code quality improvements based on the reports by Jenkins.

Code quality improvements

---

Jenkinsfile

* Docker containers are removed after usage
* push-to-stable stage enabled again

Added Jenkinsfile that supports pushing to master.

---

kieker-common/src/kieker/common/record/io/DefaultValueDeserializer.java
kieker-common/src/kieker/common/record/io/DefaultValueSerializer.java
kieker-common/src/kieker/common/record/io/IValueDeserializer.java
kieker-common/src/kieker/common/record/io/IValueSerializer.java

As requested in issue KIEKER-1555, missing base types have been added

Added missing base types to value serializers and deserializers

---

gradle.properties
kieker-monitoring/build.gradle
kieker-monitoring/src/kieker/monitoring/probe/spring/flow/RestConstants.java
kieker-monitoring/src/kieker/monitoring/probe/spring/flow/RestInFilter.java
kieker-monitoring/src/kieker/monitoring/probe/spring/flow/RestOutInterceptor.java

Replaces pull request #25 as the containing filters/interceptors are overhauled versions.

Kieker 1465 rest interceptors

---

kieker-tools/build.gradle
kieker-tools/src/kieker/tools/bridge/cli/CLIServerMain.java
kieker-tools/src/kieker/tools/bridge/connector/jms/JMSClientConnector.java

Fixed using IValueDeserializer. Also switched to JCommander.

Kieker 1007 kieker bridge jms text message processing is unsafe

---

kieker-tools/build.gradle

changed build dependency JCommander down to 1.27 from 1.60 to

---

build.gradle

* fixes https://github.com/aaschmid/gradle-cpd-plugin/issues/21
Good things come to those who wait. I eventually fixed your problem and created the pull request to share my fix :-)

Get CPD working with Gradle properly

---

build.gradle
gradle.properties
kieker-common/model/records/flow/trace/Trace.irl
kieker-common/src-gen/kieker/common/record/flow/trace/BeforeReceivedRemoteEvent.java
kieker-common/src-gen/kieker/common/record/flow/trace/BeforeReceivedRemoteEventFactory.java
kieker-common/src-gen/kieker/common/record/flow/trace/BeforeSentRemoteEvent.java
kieker-common/src-gen/kieker/common/record/flow/trace/BeforeSentRemoteEventFactory.java
kieker-monitoring/build.gradle
kieker-monitoring/src/kieker/monitoring/probe/aspectj/spring/RestCommunicationAspect.java

Relates to https://kieker-monitoring.atlassian.net/browse/KIEKER-1658

Felix' contribution

---

Jenkinsfile

Adds support for visualizing results from the pipeline:
* PMD
* Checkstyle
* Findbugs
* JUnit

Kieker 1592 static analysis reports for jenkins

---

.pmd
gradle.properties
kieker-common/model/records/database/Database.irl
kieker-common/src-gen/kieker/common/record/database/AfterDatabaseEvent.java
kieker-common/src-gen/kieker/common/record/database/AfterDatabaseEventFactory.java
kieker-common/src-gen/kieker/common/record/database/BeforeDatabaseEvent.java
kieker-common/src-gen/kieker/common/record/database/BeforeDatabaseEventFactory.java
kieker-common/src-gen/kieker/common/record/database/DatabaseFailedEvent.java
kieker-common/src-gen/kieker/common/record/database/DatabaseFailedEventFactory.java
kieker-monitoring/src/kieker/monitoring/probe/aspectj/database/AbstractAspect.java
kieker-monitoring/src/kieker/monitoring/probe/aspectj/database/Fullinstrumentation.java

Integrated DatabaseEvent probes and aspect for JDBC monitoring.
Related to Issue KIEKER-1382. Can be extended in the future.

Kieker-1382

---

Jenkinsfile

just a test to disallow a PR to a target branch

added check for PR in Jenkinsfile

---

.github/PULL_REQUEST_TEMPLATE.md

- Added a template for the description of pull requests to streamline the review process
- It asks for a short description of the actual contribution
- It asks whether code quality thresholds needed to be increased and if yes, which and why.
..

KIEKER-1747: Created pull request description template

---

kieker-analysis/src/kieker/analysisteetime/plugin/reader/filesystem/DirectoryReaderStage.java
kieker-documentation/userguide/bibliography.bib
kieker-tools/src/kieker/tools/common/AbstractService.java

Fixed the issue with the reader, which tried to read a map file as log file. This issue also would have caused trouble when finding log file formats which are not supported by the current implementation and setup.
- Bugfix of kieker teetime file reader
- Minor annoyance in AbstractService
No thresholds changed.

updated reader and fixed minor abstract service issue

---

kieker-common/model/records/flow/Flow.irl
kieker-common/src-gen/kieker/common/record/database/AfterDatabaseEvent.java
kieker-common/src-gen/kieker/common/record/database/BeforeDatabaseEvent.java
kieker-common/src-gen/kieker/common/record/database/DatabaseFailedEvent.java
kieker-common/src-gen/kieker/common/record/flow/AbstractEvent.java
kieker-common/src-gen/kieker/common/record/flow/IEventRecord.java

- Allow IEventRecords to be properly rewritten
No change in code quality setting

Fixed typo and made the timestamp changable

---

Jenkinsfile

- Separate "Archive Artifacts" stage in the build pipeline and moved it after the release checks
- Set an option that keeps the last 10 artifacts of a build and deletes the ones older than that (to save storage space on the Jenkins master); according to the documentation, this only affects the artifacts and not the other build information (e.g., logs)
- Cleanup to improve readability

Kieker 1548 jenkins declarative pipeline

---

Jenkinsfile

This pull request provides the following contribution to Kieker:
- Renamed "Docker Stages" stage group to "Default Docker Stages".
- Moved 'master'-specific stages into one group with each stage being able to be executed in parallel
- Enabled fast-fail for parallel stages (i.e., if one stage in a parallel block fails, the whole parallel block fails immediately).
- Removed some debug output and unnecessary comments from Jenkinsfile.

Kieker 1548 jenkins declarative parallelism

---

kieker-analysis/src/kieker/analysisteetime/plugin/reader/filesystem/DirectoryReaderStage.java
kieker-analysis/src/kieker/analysisteetime/plugin/reader/filesystem/DirectoryScannerStage.java
kieker-documentation/userguide/bibliography.bib
kieker-tools/src/kieker/tools/common/AbstractLegacyTool.java
kieker-tools/src/kieker/tools/common/AbstractService.java
kieker-tools/src/kieker/tools/trace/analysis/TraceAnalysisToolMain.java

- Improved logging output
- Name sorted directory reading. Previously the directory scanner and file reader were reading directories and files in system order, which might not be alphabetically.
No changes in thresholds

minor fixes

---

bin/dev/release-check-extended.sh
kieker-analysis/src/kieker/analysis/plugin/reader/filesystem/BinaryFileStreamProcessor.java
kieker-analysis/src/kieker/analysis/plugin/reader/util/FSReaderUtil.java
kieker-analysis/src/kieker/analysisteetime/plugin/reader/filesystem/DirectoryReaderStage.java
kieker-analysis/src/kieker/analysisteetime/plugin/reader/filesystem/format/binary/file/RecordFromBinaryFileCreator.java
kieker-analysis/test/kieker/test/analysis/util/AssertHelper.java

- Some missing cleanup
- Fix of handling files without extension in kieker log directories (aka garbage files created by the user)
- No change in thresholds

Kieker 1754 convert tools to multi project builds

---

kieker-analysis/gradle.properties
kieker-common/gradle.properties
kieker-tools/collector/gradle.properties
kieker-tools/convert-logging-timestamp/gradle.properties
kieker-tools/gradle.properties
kieker-tools/kdb/gradle.properties
kieker-tools/trace-analysis/gradle.properties

- Reduced static analysis thresholds.
- Code quality thresholds have been reduced.
..

KIEKER-1783: Reduced thresholds for static analysis.

---

Jenkinsfile
build.gradle
config/checkstyle-noframes-severity-sorted.xsl

- Changed stylesheet for Checkstyle reports to show severities of issues
- Added generation of HTML reports for PMD
- Static Analysis Reports (PMD/CheckStyle/FindBugs) will be reported even if thresholds are exceeded
- Updated Jenkinsfile to use the new Warnings-NG plugin

Kieker 1786 proper static analysis reports

---

kieker-analysis/src/kieker/analysis/source/rest/RestServiceStage.java
kieker-analysis/src/kieker/analysis/source/tcp/Connection.java
kieker-analysis/src/kieker/analysis/source/tcp/MultipleConnectionTcpSourceStage.java
kieker-analysis/src/kieker/analysis/source/tcp/ReaderThread.java
kieker-tools/collector/collector.properties
kieker-tools/src/kieker/tools/common/AbstractService.java

This pull request provides the following contribution to Kieker:
- Fixes high CPU load of multi connection TCP stage

KIEKER-1790 Reworked multi connection tcp stage to cost less CPU time.

---

kieker-common/model/records/remotecontrol/RemoteControl.irl
kieker-common/src-gen/kieker/common/record/remotecontrol/ActivationParameterEvent.java
kieker-common/src-gen/kieker/common/record/remotecontrol/IRemoteParameterControlEvent.java
kieker-common/src-gen/kieker/common/record/remotecontrol/UpdateParameterEvent.java
kieker-documentation/userguide/bibliography.bib
kieker-monitoring/src/kieker/monitoring/core/controller/IProbeController.java
kieker-monitoring/src/kieker/monitoring/core/controller/MonitoringController.java
kieker-monitoring/src/kieker/monitoring/core/controller/ProbeController.java
kieker-monitoring/src/kieker/monitoring/listener/MonitoringCommandListener.java
kieker-monitoring/test/kieker/monitoring/core/controller/TCPControllerTest.java

- Intproved the parameter setting in the monitoring controller at runtime.
- No threasholds were changed

Kieker 1794 support for different probe parameter sizes

---

Jenkinsfile
bin/dev/release-check-common.sh
bin/dev/release-check-extended.sh
bin/dev/release-check-short.sh
build.gradle
kieker-documentation/userguide/bibliography.bib
kieker-documentation/userguide/build.gradle
kieker-examples/userguide/ch5--trace-monitoring-aspectj/testdata/kieker-20100830-082225522-UTC-example-plots.sh
kieker-examples/userguide/ch5--trace-monitoring-aspectj/testdata/kieker-20141008-101258768-UTC-example-plots.sh
kieker-examples/userguide/ch5--trace-monitoring-aspectj/testdata/kieker-20141008-101258768-UTC-repairEventBasedTraces-example-plots.sh
kieker-examples/userguide/ch5--trace-monitoring-aspectj/testdata/kieker-20141009-160413833-UTC-operationExecutionsConstructors-example-plots.sh
kieker-examples/userguide/ch5--trace-monitoring-aspectj/testdata/kieker-20141009-163010944-UTC-constructor-events-example-plots.sh

- Fixes for new build container

Jenkins testing

---

Jenkinsfile

Increased timeout.

---

Jenkinsfile
pw

Still working to fix the Jenkinsfile to be able to push to stable

Jenkins upgrade

---

CITATION.cff
README.md
codemeta.json

- Added citation references to the README
- Added CITATION file
- Added codemeta json, as citation file
..

KIEKER-1792: Provide CiteAs data for Kieker

---

Kieker.bib
README.md

- Kieker.bib as BibTeX file
- Link from the README to this BibTeX file
No

Added Kieker BibTeX file

---

build.gradle
kieker-documentation/userguide/bibliography.bib
kieker-tools/collector/build.gradle
kieker-tools/convert-logging-timestamp/build.gradle
kieker-tools/kdb/build.gradle
kieker-tools/log-replayer/build.gradle
kieker-tools/resource-monitor/build.gradle
kieker-tools/trace-analysis-gui/build.gradle
kieker-tools/trace-analysis/build.gradle

- Fixing upload archives to sonatype

HAcked to ignore tools

---

build.gradle

Changed output location for upload

---

Jenkinsfile
bin/dev/release-check-extended.sh
bin/dev/release-check-short.sh
build.gradle
kieker-monitoring/gradle.properties
kieker-tools/build.gradle
kieker-tools/collector/build.gradle
kieker-tools/convert-logging-timestamp/build.gradle
kieker-tools/kdb/build.gradle
kieker-tools/log-replayer/build.gradle
kieker-tools/opad/build.gradle
kieker-tools/resource-monitor/build.gradle
kieker-tools/trace-analysis-gui/build.gradle
kieker-tools/trace-analysis/build.gradle

- Removed script start tasks from gradle and now start the task within the Jenkinsfile directly.
- Minor cleanups.
- Increased findbugs check (temporarily), as there seem to be more issues without any code changes (version side effects?)

Kieker 1839 cleanup build script

---

kieker-monitoring/build.gradle
kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/flow/TestBeforeAfterConstructorEvent.java
kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/flow/TestBeforeAfterOperationEvent.java
kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/operationExecution/StreamGobbler.java
kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/operationExecution/TestOperationExecutionInstrumentation.java
kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/operationExecution/Util.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/.gitignore
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/build.gradle
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestOperationExecutionException.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestSimpleOperationExecution.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/src/test/java/net/example/Instrumentable.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafterconstructorevent/src/test/resources/META-INF/aop.xml
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/.gitignore
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/build.gradle
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestOperationExecutionException.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestSimpleOperationExecution.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/src/test/java/net/example/Instrumentable.java
kieker-monitoring/test-resources/example-projects-aspectj/example-beforeafteroperationevent/src/test/resources/META-INF/aop.xml
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/.gitignore
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/build.gradle
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestOperationExecutionException.java
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/src/test/java/kieker/monitoring/probe/aspectj/operationExecution/TestSimpleOperationExecution.java
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/src/test/java/net/example/Instrumentable.java
kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/src/test/resources/META-INF/aop.xml

According to https://kieker-monitoring.atlassian.net/browse/KIEKER-1866, I added a jarIntegrationTest task to the `build.gradle`, three tests (including example projects) testing the instrumentation of OperationExecutionEvents, the `kieker.monitoring.probe.aspectj.flow.constructorExecution.FullInstrumentation` and `kieker.monitoring.probe.aspectj.flow.operationExecution.FullInstrumentation` are added.
- Contribution 1: Configuration of `jarIntegrationTest` task
- Contribution 2: Unit tests and example projects

Add jarIntegrationTest phase and tests

---

kieker-analysis/gradle.properties
kieker-analysis/src/kieker/analysis/model/AbstractModelAssembler.java
kieker-analysis/src/kieker/analysis/source/file/DirectoryReaderStage.java
kieker-analysis/test/kieker/analysis/dependencygraphs/TypeLevelComponentDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/model/AbstractModelAssemblerTest.java
kieker-analysis/test/kieker/analysis/model/TypeModelAssemblerTest.java
kieker-analysis/test/kieker/analysis/sink/EquivalenceClassWriterTest.java
kieker-analysis/test/kieker/analysis/stage/DynamicEventDispatcherTest.java
kieker-analysis/test/kieker/analysis/stage/flow/EventRecordTraceReconstructionStageTest.java
kieker-analysis/test/kieker/analysis/stage/flow/ThreadEvent2TraceEventStageTest.java
kieker-analysis/test/kieker/analysis/stage/flow/TraceRecordsTraceReconstructionStageTest.java
kieker-analysis/test/kieker/analysis/trace/EventRecordTraceCounterTest.java
kieker-analysis/test/kieker/analysis/tt/writeRead/jms/FakeConnection.java
kieker-analysis/test/kieker/analysis/tt/writeRead/jms/FakeConnectionFactory.java
kieker-analysis/test/kieker/analysis/util/bookstore/package-info.java
kieker-analysis/test/kieker/test/analysis/util/plugin/filter/SimpleForwardFilterWithRepository.java

- Minor fixes
- Reduced checkstyle errors
- Added two tests for model assemblers

Kieker 1869 extend architecture model

---

kieker-analysis/src/kieker/analysis/plugin/reader/filesystem/AsciiLogReaderThread.java
kieker-analysis/src/kieker/analysis/plugin/reader/filesystem/BinaryLogReaderThread.java
kieker-analysis/src/kieker/analysis/plugin/reader/filesystem/FSDirectoryReader.java
kieker-analysis/src/kieker/analysis/plugin/reader/filesystem/FSZipReader.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/className/ClassNameRegistryCreationFilter.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/format/binary/file/BinaryFile2RecordFilter.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/fsReader/AsciiLogReaderThread.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/fsReader/BinaryLogReaderThread.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/fsReader/FSDirectoryReader.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/fsReader/FSZipReader.java
kieker-analysis/test/kieker/analysis/configuration/DependencyGraphConfigurationTest.java
kieker-analysis/test/kieker/test/analysis/util/StringUtils.java
kieker-common/src/kieker/common/util/filesystem/BinaryCompressionMethod.java
kieker-monitoring/src/kieker/monitoring/core/controller/ProbeController.java
kieker-monitoring/src/kieker/monitoring/writer/filesystem/AbstractLogStreamHandler.java
kieker-monitoring/test/kieker/test/monitoring/junit/core/controller/TestProbeController.java
kieker-tools/kdb/src/kieker/tools/bridge/cli/CLIServerMain.java
kieker-tools/src/kieker/tools/trace/analysis/repository/TraceColorRepository.java
kieker-tools/trace-analysis-gui/src/kieker/tools/trace/analysis/ui/TraceAnalysisGUI.java

Also might fixed issue with log stream handler.
- Changed file IO from new Inputstream to Files.newInputStream
- No changes.

KIEKER-1873 fixed in/out issue with new InputStream/OutputStream.

---

kieker-analysis/src/kieker/analysis/graph/export/dot/DotFileWriterStage.java
kieker-monitoring/src/kieker/monitoring/probe/disl/flow/operationExecution/FullInstrumentation.java
kieker-monitoring/src/kieker/monitoring/writer/filesystem/MappingFileWriter.java
kieker-monitoring/src/kieker/monitoring/writer/filesystem/TextMapFileHandler.java
kieker-monitoring/test/kieker/monitoring/writer/filesystem/TextMapFileHandlerTest.java

- Fixed file writing and especially overwriting feature.
- No change

KIEKER-1873 fixed file (over-)writing in Kieker.

---

gradle.properties
kieker-examples/monitoring/probe-spring/build.gradle
kieker-monitoring/build.gradle

- Upgraded spring dependencies to 5.3.1
- Fixed example
- No thresholds were changed.

KIEKER-1824 fixed spring example.

---

build.gradle
gradle.properties
kieker-analysis/build.gradle
kieker-monitoring/build.gradle
kieker-tools/build.gradle

- Contribution 1 Store versions of junit, slf4j and amqp in gradle.properties
..

Store versions of junit, slf4j and amqp in gradle.properties

---

build.gradle
gradle.properties
kieker-analysis/build.gradle
kieker-analysis/src/kieker/analysis/plugin/reader/database/DbReader.java
kieker-common/build.gradle
kieker-examples/monitoring/probe-spring/build.gradle
kieker-monitoring/build.gradle
kieker-tools/build.gradle
kieker-tools/opad/build.gradle

- Contribution 1 Update the dependencies of most libraries, excluding amqp, jetty, guava, oshi and derby
..

Update Library Versions

---

kieker-analysis/build.gradle
kieker-analysis/src/kieker/analysis/stage/model/AssemblyModelAssembler.java
kieker-model/model/analysismodel.ecore
kieker-model/model/analysismodel.genmodel
kieker-model/src-gen/kieker/model/analysismodel/assembly/AssemblyComponent.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/AssemblyPackage.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/AssemblyComponentImpl.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/AssemblyPackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/DeployedComponent.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/DeploymentPackage.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/impl/DeployedComponentImpl.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/impl/DeploymentPackageImpl.java

- Fixed missing model attribute.
- No changes here

KIEKER-1889 added signature to assembly component.

---

kieker-model/model/analysismodel.ecore
kieker-model/model/analysismodel.genmodel
kieker-model/src-gen/kieker/model/analysismodel/assembly/AssemblyPackage.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/AssemblyStorage.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/AssemblyPackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/AssemblyStorageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/DeployedStorage.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/DeploymentPackage.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/impl/DeployedStorageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/deployment/impl/DeploymentPackageImpl.java

- Fixed names of references.
No changes here.

KIEKER-1889 fixed reference names for storage part of the model.

---

kieker-model/model/analysismodel.ecore
kieker-model/model/analysismodel.genmodel
kieker-model/src-gen/kieker/model/analysismodel/execution/EDirection.java
kieker-model/src-gen/kieker/model/analysismodel/execution/ExecutionModel.java
kieker-model/src-gen/kieker/model/analysismodel/execution/ExecutionPackage.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/DeployedOperationsPairToAggregatedStorageAccessMapEntryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionFactoryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionModelImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionPackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/util/ExecutionAdapterFactory.java
kieker-model/src-gen/kieker/model/analysismodel/execution/util/ExecutionSwitch.java

- Fixed architecture model
- No changes necessary
..

Kieker 1889

---

kieker-analysis/src/kieker/analysis/graph/dependency/vertextypes/VertexType.java

- Fixed number of vertex types.
..

KIEKER-1894 extended set of vertex types.

---

kieker-analysis/src/kieker/analysis/graph/dependency/AssemblyLevelComponentDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/AssemblyLevelOperationDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/BasicDependencyGraphBuilderConfiguration.java
kieker-analysis/src/kieker/analysis/graph/dependency/DeploymentLevelComponentDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/DeploymentLevelOperationDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/IDependencyGraphBuilderConfiguration.java
kieker-analysis/src/kieker/analysis/graph/dependency/IDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/TypeLevelComponentDependencyGraphBuilderFactory.java
kieker-analysis/src/kieker/analysis/graph/dependency/TypeLevelOperationDependencyGraphBuilderFactory.java
kieker-analysis/test/kieker/analysis/dependencygraphs/AssemblyLevelComponentDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/AssemblyLevelOperationDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/DeploymentLevelComponentDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/DeploymentLevelContextDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/DeploymentLevelOperationDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/TypeLevelComponentDependencyGraphBuilderFactoryTest.java
kieker-analysis/test/kieker/analysis/dependencygraphs/TypeLevelOperationDependencyGraphBuilderFactoryTest.java
kieker-tools/kdb/test/kieker/test/tools/junit/bridge/ConfigurationParameters.java

- Further fixes on graph visualization
..

Kieker 1894

---

kieker-analysis/src/kieker/analysis/ExampleConfiguration.java
kieker-analysis/src/kieker/analysis/configuration/DependencyGraphConfiguration.java
kieker-analysis/src/kieker/analysis/graph/dependency/DependencyGraphCreatorStage.java

KIEKE-1894 furhter imporved the API

---

kieker-documentation/requirements.txt

KIEKER-1907 fiddling with versions.

---

kieker-analysis/src/kieker/analysis/source/file/TextMapDeserializer.java
kieker-analysis/src/kieker/analysis/tt/reader/filesystem/fsReader/BinaryLogReaderThread.java
kieker-common/src/kieker/common/util/classpath/InstantiationFactory.java
kieker-tools/src/kieker/tools/trace/analysis/filter/visualization/callTree/AggregatedAllocationComponentOperationCallTreeFilter.java
kieker-tools/test/kieker/test/tools/junit/writeRead/explorviz/CustomAfterOperationEvent.java

Resolved a set of minor issues reported by static analysis.
..

Kieker 1789 static analysis cleanup

---

kieker-monitoring/src/kieker/monitoring/probe/aspectj/flow/constructorExecution/AbstractAspect.java
kieker-monitoring/src/kieker/monitoring/probe/aspectj/flow/constructorExecutionObject/AbstractAspect.java
kieker-monitoring/src/kieker/monitoring/probe/aspectj/flow/constructorExecutionObjectInterface/AbstractAspect.java
kieker-monitoring/test/kieker/OSUtil.java
kieker-monitoring/test/kieker/monitoring/core/controller/TCPControllerTest.java
kieker-monitoring/test/kieker/monitoring/writer/influxdb/InfluxDBWriterFailingTest.java

- Contribution 1 Add `OSUtil` that tells whether the current build is on windows. I added it as a general util in the `kieker` package, like `Await`.
- Contribution 2 Add `Assume.assumeFalse` to failing tests, so they are not executed on windows builds.
..

Skip Tests on Windows to Avoid Github Actions Failures

---

kieker-documentation/kieker-tools/irl/overview.rst

Updated IRL documentation.

---

kieker-documentation/analyzing-monitoring-data/Analyzing-Monitoring-Data.rst
kieker-documentation/analyzing-monitoring-data/How-to-perform-Trace-Analysis.rst
kieker-documentation/collecting-data/Collecting-Data.rst
kieker-documentation/conf.py
kieker-documentation/developing-with-kieker/Developing-with-Kieker.rst
kieker-documentation/developing-with-kieker/How-to-Write-Probes.rst
kieker-documentation/developing-with-kieker/How-to-Write-Stages.rst
kieker-documentation/developing-with-kieker/Writing-your-own-Analysis-Stages.rst
kieker-documentation/getting-started/Getting-Started.rst
kieker-documentation/index.rst
kieker-documentation/instrumenting-software/Instrumenting-Software.rst
kieker-documentation/instrumenting-software/java/Controlling-At-Runtime.rst
kieker-documentation/instrumenting-software/java/How-to-Use-JMS-for-Monitoring.rst
kieker-documentation/instrumenting-software/java/How-to-apply-Instrumentation.rst
kieker-documentation/instrumenting-software/java/Java.rst
kieker-documentation/kieker-tools/Kieker-Tools.rst
kieker-documentation/kieker-tools/irl/overview.rst
kieker-documentation/lectures/201403-ICPE-Dublin.rst
kieker-documentation/lectures/201405-University-Pavia.rst
kieker-documentation/lectures/Lectures.rst
kieker-documentation/lexers.py
kieker-documentation/technical-details/Technical-Details.rst
kieker-documentation/technical-details/java/writer/api.rst

Kieker 1915 improove documentation for irl

---

kieker-documentation/conf.py

- Adjusted theme colors and theme to match Kieker colors

KIEKER-1915 recolored theme.

---

kieker-analysis/gradle.properties
kieker-common/gradle.properties
kieker-extension-cassandra/gradle.properties
kieker-model/build.gradle
kieker-model/gradle.properties
kieker-model/src/kieker/model/repository/SystemModelRepository.java
kieker-model/src/kieker/model/system/model/AbstractSession.java
kieker-model/src/kieker/model/system/model/ComponentType.java
kieker-model/src/kieker/model/system/model/Execution.java
kieker-model/src/kieker/model/system/model/ExecutionContainer.java
kieker-model/src/kieker/model/system/model/Operation.java

- Lowered quality thresholds
- Added models

Kieker 1916 remove deprecated classes

---

kieker-model/model/analysiscollections.ecore
kieker-model/src-gen/kieker/model/collection/CollectionPackage.java
kieker-model/src-gen/kieker/model/collection/Connections.java
kieker-model/src-gen/kieker/model/collection/impl/CollectionFactoryImpl.java
kieker-model/src-gen/kieker/model/collection/impl/CollectionPackageImpl.java
kieker-model/src-gen/kieker/model/collection/impl/ConnectionsImpl.java
kieker-model/src-gen/kieker/model/collection/impl/CouplingToOperationMapImpl.java
kieker-model/src-gen/kieker/model/collection/util/CollectionAdapterFactory.java
kieker-model/src-gen/kieker/model/collection/util/CollectionSwitch.java

- Minor fixes to the collection model

KIEKER-1916 minor fix in model.

---

kieker-model/model/analysismodel.ecore
kieker-model/src-gen/kieker/model/analysismodel/AnalysismodelPackage.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/AssemblyPackage.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/AssemblyPackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/assembly/impl/EStringToAssemblyProvidedInterfaceMapEntryImpl.java

- Fixed missing containment in assembly model

KIEKER-1916 minor bug in analysismetamodel in containment hierarchy.

---

kieker-model/model/analysismodel.ecore
kieker-model/model/analysismodel.genmodel
kieker-model/src-gen/kieker/model/analysismodel/type/ProvidedInterfaceType.java
kieker-model/src-gen/kieker/model/analysismodel/type/TypePackage.java
kieker-model/src-gen/kieker/model/analysismodel/type/impl/InterfaceEStringToOperationTypeMapEntryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/type/impl/ProvidedInterfaceTypeImpl.java
kieker-model/src-gen/kieker/model/analysismodel/type/impl/TypeFactoryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/type/impl/TypePackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/type/util/TypeAdapterFactory.java
kieker-model/src-gen/kieker/model/analysismodel/type/util/TypeSwitch.java

KIEKER-1916 updated model.

---

kieker-analysis/build.gradle
kieker-examples/analysis/trace-analysis/build.gradle

Kieker 1921 teetime upgrade

---

.github/workflows/gradle.yml
.github/workflows/gradleForPR.yml
gradle.properties

- Contribution 1 Update Github Actions to Java 17 and 18
..

Update Java Versions for Github Actions Build

---

Jenkinsfile

- Fixed Jenkinsfile (hopefully)
..

KIEKER-1926 fixed Jenkins

---

Jenkinsfile

KIEKER-1926 still issues with Jenkinsfile

---

Jenkinsfile

KIEKER-1926 fiddling with Jenkinsfile

---

kieker-analysis/src/kieker/analysis/generic/time/TimestampFilter.java
kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/TraceAnalysisParameters.java
kieker-tools/trace-analysis/test/kieker/test/tools/manual/TestAnalysis.java
kieker-tools/trace-analysis/test/kieker/test/tools/manual/TestExplorVizExportWriter.java

KIEKER-1920 minor fix.

---

kieker-analysis/src/kieker/analysis/architecture/dependency/AbstractDependencyGraphBuilder.java
kieker-analysis/src/kieker/analysis/architecture/recovery/ExecutionModelAssembler.java
kieker-analysis/src/kieker/analysis/architecture/recovery/ModelObjectFromOperationCallAccessorUtils.java
kieker-analysis/src/kieker/analysis/architecture/recovery/TraceBasedExecutionModelAssembler.java
kieker-model/model/analysismodel.ecore
kieker-model/model/analysismodel.genmodel
kieker-model/src-gen/kieker/model/analysismodel/execution/ExecutionModel.java
kieker-model/src-gen/kieker/model/analysismodel/execution/ExecutionPackage.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/DeployedOperationsPairToInvocationMapEntryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionFactoryImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionModelImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/impl/ExecutionPackageImpl.java
kieker-model/src-gen/kieker/model/analysismodel/execution/util/ExecutionAdapterFactory.java
kieker-model/src-gen/kieker/model/analysismodel/execution/util/ExecutionSwitch.java

Kieker 1931 integrate dataflow support into architecture model

---

kieker-analysis/gradle.properties
kieker-analysis/src/kieker/analysis/behavior/ModelGenerationCompositeStage.java
kieker-analysis/src/kieker/analysis/behavior/UserSessionToBehaviorModelTransformation.java
kieker-analysis/src/kieker/analysis/behavior/clustering/BehaviorModelToOpticsDataTransformation.java
kieker-analysis/src/kieker/analysis/behavior/clustering/ClusteringCompositeStage.java
kieker-analysis/src/kieker/analysis/behavior/clustering/UserBehaviorCostFunction.java
kieker-analysis/src/kieker/analysis/behavior/model/UserBehaviorEdge.java
kieker-analysis/src/kieker/analysis/generic/graph/GraphFactory.java
kieker-analysis/src/kieker/analysis/generic/graph/IGraph.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/GraphEditDistance.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/MTreeGeneratorStage.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/MedoidGenerator.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/NaiveMediodGenerator.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/OPTICS.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/OpticsStage.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/TrimmedAlgorithm.java
kieker-analysis/src/kieker/analysis/generic/graph/impl/GraphImpl.java
kieker-analysis/src/kieker/analysis/generic/graph/impl/package-info.java
kieker-analysis/src/kieker/analysis/util/debug/GraphPrinterStage.java
kieker-analysis/src/kieker/analysis/util/debug/package-info.java
kieker-analysis/test/kieker/analysis/behavior/UserSessionToBehaviorModelTransformationTest.java
kieker-model/gradle.properties
kieker-monitoring/gradle.properties
kieker-tools/behavior-analysis/gradle.properties
kieker-tools/behavior-analysis/src/kieker/tools/behavior/analysis/BehaviorAnalysisConfiguration.java
kieker-tools/gradle.properties
kieker-tools/log-replayer/gradle.properties
kieker-tools/resource-monitor/gradle.properties
kieker-tools/trace-analysis-gui/gradle.properties
kieker-tools/trace-analysis/gradle.properties

- minor corrections
- lowered check limits

Kieker 1932 merge user behavior modeling

---

kieker-tools/log-replayer/src/kieker/tools/log/replayer/ReplayerMain.java
kieker-tools/log-replayer/src/kieker/tools/log/replayer/Settings.java
kieker-tools/log-replayer/src/kieker/tools/log/replayer/TeetimeConfiguration.java

- Contribution 1 Allow the replaying of multiple files
- Contribution 2 Use configuration via kieker.monitoring.properties instead individual command line parameters
..

Kieker 1948 log replayer does not work

---

kieker-tools/log-replayer/src/kieker/tools/log/replayer/ReplayerMain.java
kieker-tools/log-replayer/src/kieker/tools/log/replayer/Settings.java
kieker-tools/log-replayer/src/kieker/tools/log/replayer/TeetimeConfiguration.java

KIEKER-1948 Fixed checkstyle issues.

---

kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/DecoratorValidator.java
kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/PerformAnalysis.java
kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/TraceAnalysisParameters.java
kieker-tools/trace-analysis/test/kieker/test/tools/manual/TestAnalysis.java

- Contribution 1 Check the parameters that should contain response time units for correct values, otherwise, misunderstandings of typos lead to hard-to-trace errors
..

Check parameter for validity

---

kieker-analysis/src/kieker/analysis/architecture/recovery/assembler/AbstractModelAssembler.java
kieker-analysis/src/kieker/analysis/architecture/recovery/assembler/StorageTypeModelAssembler.java
kieker-analysis/src/kieker/analysis/architecture/recovery/assembler/package-info.java
kieker-analysis/src/kieker/analysis/architecture/recovery/signature/IStorageSignatureExtractor.java

Kieker 1959 add oceandsl features

---

kieker-monitoring/src-resources/META-INF/kieker.monitoring.default.properties
kieker-monitoring/src/kieker/monitoring/timer/SystemMilliTimer.java
kieker-monitoring/src/kieker/monitoring/timer/SystemNanoTimer.java
kieker-monitoring/test/kieker/monitoring/timer/AbstractTimeSourceTest.java
kieker-monitoring/test/kieker/monitoring/timer/SystemMilliTimerTest.java
kieker-monitoring/test/kieker/monitoring/timer/SystemNanoTimerTest.java

- Replaced old style numbers to specify time units to proper unit names

KIEKER-1459 switched from integes to enumeration for timer selection.

---

kieker-analysis/src/kieker/analysis/architecture/trace/TraceIdFilter.java
kieker-analysis/src/kieker/analysis/architecture/trace/ValidEventRecordTraceCounter.java
kieker-analysis/src/kieker/analysis/behavior/ModelGenerationCompositeStage.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/ClusteringFileSink.java
kieker-analysis/src/kieker/analysis/generic/graph/clustering/OPTICS.java
kieker-analysis/src/kieker/analysis/stage/model/MetaModelHandler.java
kieker-analysis/test/kieker/analysis/architecture/trace/TraceIdFilterTest.java
kieker-monitoring/src/kieker/monitoring/probe/aspectj/flow/constructorExecution/AbstractAspect.java
kieker-tools/behavior-analysis/src/kieker/tools/behavior/analysis/BehaviorAnalysisConfiguration.java
kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/TraceAnalysisConfiguration.java
kieker-tools/trace-analysis/src/kieker/tools/trace/analysis/TraceAnalysisParameters.java

Kieker 1855 port trace analysis

---

kieker-tools/mvis/src/kieker/tools/mvis/graph/DotExportConfigurationFactory.java

KIEKER-1959 minor fix.

---

kieker-documentation/kieker-tools/Kieker-Tools.rst

Fix links in rst

---

kieker-documentation/conf.py
kieker-documentation/developing-with-kieker/New-Trace-Analysis.rst

Fixed documentation.

---

kieker-documentation/requirements.txt

- debugging documentation generation

Fixed requirements

---

kieker-documentation/kieker-tools/static-analysis-formats.rst

minor fix it.

---

analysis/build.gradle
build.gradle
common/build.gradle
monitoring/build.gradle
tools/build.gradle

- try to fix deployment group info

KIEKER-1933 Updated infos for publishing.

---

model/build.gradle

KIEKER-1933 updated snapshot upload.

---

documentation/conf.py
documentation/developing-with-kieker/java/Kieker-Analysis-Metamodel.rst
documentation/index.rst
documentation/quick-start-guide.rst
documentation/requirements.txt

KIEKER-1901 updated documentation

---

documentation/.readthedocs.yaml

KIEKER-1901 update to new readthedocs setup.

---

documentation/.readthedocs.yaml

KIEKER-1901 updated setup

---

documentation/requirements.txt

KIEKER-1901 updated docutils.

---

documentation/requirements.txt

KIEKER-1901 still fixing dependencies with sphinx.

---

monitoring/build.gradle

- Contribution 1 The aopalliance dependency, that is not required, is removed now
..

Remove aopalliance dependency

---

gradle.properties

- Contribution 1 Since 1.9.21 does not work as expected, update to 1.9.20.1 for now.
..

As an intermediary solution, update to 1.9.20.1

---

gradle.properties
monitoring/build.gradle

- Contribution 1 Update AspectJ to 1.9.21 to support JDK 21
..

Update AspectJ to 1.9.21 to support JDK 21 monitoring

---

build.gradle
examples/analysis/trace-analysis/gradle.properties

KIEKER-1974 minor fix in examples.

---

bin/dev/release-check-extended.sh
bin/dev/release-check-short.sh
tools/sar/test/kiekerl/tools/sar/stages/dataflow/CleanupDataflowComponentSignatureStageTest.java
tools/sar/test/kiekerl/tools/sar/stages/dataflow/CountUniqueDataflowCallsStageTest.java
tools/sar/test/kiekerl/tools/sar/stages/dataflow/ElementAndDataflow4StaticDataStageTest.java
tools/sar/test/kiekerl/tools/sar/stages/dataflow/ExecutionModelDataflowAssemblerStageTest.java

- Contribution 1 Tests that are failing are disabled now
..

Disable failing tests

---

monitoring/README.md

- Contribution 1 Fix space that has been created by merge
..

Fix spotless after merge (otherwise, every PR etc. will not work)

---

analysis/build.gradle
build.gradle
common/build.gradle
extension-cassandra/build.gradle
extension-kafka/build.gradle
model/build.gradle
monitoring/README.md
monitoring/aspectj/build.gradle
monitoring/aspectj/integrationTest-resources/example-projects-aspectj/example-beforeafterconstructorevent/build.gradle
monitoring/aspectj/integrationTest-resources/example-projects-aspectj/example-beforeafteroperationevent/build.gradle
monitoring/aspectj/integrationTest-resources/example-projects-aspectj/example-operationexecutionrecord/build.gradle
monitoring/aspectj/integrationTest-resources/example-projects-aspectj/example-pure/build.gradle
monitoring/core/build.gradle
monitoring/disl/build.gradle
tools/build.gradle

- Contribution 1 Cleanup build.gradle to increase maintainability
..

Kieker 1979 unclarities build.gradle

---

monitoring/core/gradle.properties
monitoring/core/src/kieker/monitoring/probe/utilities/FullOperationStartData.java
monitoring/core/src/kieker/monitoring/probe/utilities/OperationExecutionDataGatherer.java
monitoring/core/src/kieker/monitoring/probe/utilities/OperationStartData.java
monitoring/disl/gradle.properties
monitoring/disl/src/kieker/monitoring/probe/disl/flow/operationExecution/KiekerStaticContext.java
monitoring/disl/src/kieker/monitoring/probe/disl/flow/operationExecution/OperationExecutionDiSL.java

PR https://github.com/kieker-monitoring/kieker/pull/510 seems to have been automatically closed since the changes where in https://github.com/kieker-monitoring/kieker/pull/529. Therefore, I create a new PR for fixing the formatting problems.
- Contribution 1 Fix formatting as discussed in #510
..

Fix formatting after new DiSL probe creation

---

gradle.properties

This PR should be merged after #533 
- Contribution 1 Update AspectJ to 1.9.22
..

Update to AspectJ 1.9.22

---

bin/dev/Jenkinsfile-TestVersionChange

- Check to release check Jenkinsfile
..

KIEKE-1809 possible fix for release check.

---

bin/dev/Jenkinsfile-TestVersionChange

KIEKER-1809 minor adjustments.

---

documentation/kieker-tools/dar.rst
documentation/requirements.txt

- fiddling with documentation generation

Kieker 1982

---

bin/dev/Jenkinsfile-TestVersionChange

Kieker 1809

---

bin/dev/Jenkinsfile-TestVersionChange

KIEKER-1809 fiddling with build system

---

bin/dev/Jenkinsfile-TestVersionChange

KIEKER-1809

---

.github/workflows/gradle.yml
.github/workflows/gradleForPR.yml

- Contribution 1 Update GH Actions `checkout` and `setup-java` to v4
..

Kieker 1985 update gh actions

---

bin/dev/Jenkinsfile-TestVersionChange

KIEKER-1809 meh

---

bin/dev/Jenkinsfile-TestVersionChange

KIEKE-1809 meh 3

---

Jenkinsfile
monitoring/aspectj/build.gradle
monitoring/core/build.gradle
monitoring/disl/build.gradle
monitoring/spring/build.gradle

- Contribution 1 Use the `OSSRH-Token` for new sonatype authentication
- Contribution 2 Rename `monitoring` artifacts, so they don't overwrite each other
..

Kieker 1988 fix snapshot upload

---

gradle.properties

- Contribution 1 Update AspectJ to 1.9.22.1 (minor bugfix release)
..

Update AspectJ to 1.9.22.1

---

.github/workflows/gradle.yml
.github/workflows/gradleForPR.yml

- Contribution 1 Update GH Actions versions
..

Kieker 1985 update upload

---

build.gradle
monitoring/bytebuddy/gradle.properties
monitoring/bytebuddy/src/kieker/monitoring/probe/bytebuddy/InstrumentationEnvironmentVariables.java
monitoring/bytebuddy/src/kieker/monitoring/probe/bytebuddy/PremainClass.java
monitoring/core/src/kieker/monitoring/util/KiekerPatternUtil.java

- Contribution 1 Add option for ByteBuddy instrumentation to exclude
- Contribution 2 Fix current checking to check for wildcards correctly
..

Kieker 1998 exclusion byte buddy

---

monitoring/README.md
monitoring/aspectj/src/kieker/monitoring/probe/aspectj/AbstractAspectJProbe.java
monitoring/bytebuddy/gradle.properties
monitoring/bytebuddy/src/kieker/monitoring/probe/bytebuddy/PremainClass.java

- Contribution 1 Enable lambda logging for the ByteBuddy agent
- Contribution 2 Don't append a space for parameter lists in AspectJ, to make results more comparable to ByteBuddy
..

Kieker 1973 fix bytebuddy lambda

---

tools/otel-transformer/src/kieker/tools/oteltransformer/stages/OpenTelemetryExporterStage.java

- Contribution 1 Make ExplorViz token and secret configurable
..

Kieker 2001 explor viz token

---

build.gradle

- It adds a new developer entry

Adds a new developer

---

README.md
build.gradle
monitoring/README.md

- Contribution 1 Add tracing to use up-to-date terminology
..

Add tracing to use up-to-date terminology

---

tools/build.gradle
tools/opad/src/kieker/tools/opad/timeseries/forecast/AbstractRForecaster.java
tools/opad/src/kieker/tools/opad/timeseries/forecast/InvalidREvaluationResultException.java
tools/opad/src/kieker/tools/opad/timeseries/forecast/OutputStream2StandardLog.java
tools/opad/src/kieker/tools/opad/timeseries/forecast/RBridgeControl.java
tools/opad/test/kieker/test/tools/junit/rbridge/RBridgeTest.java

- Contribution 1 Move R dependencies to opad
..

Kieker 2006 r dependencies to opad

---

tools/build.gradle

- Contribution 1 Remove unused groovy dependency
- Contribution 2 Remove unused activemq dependency
..

Remove unused groovy dependency

---

tools/restructuring/build.gradle

- Contribution 1 Remove unused lombok
..

Remove unused lombok

---

gradle.properties
monitoring/aspectj/build.gradle
monitoring/core/build.gradle
tools/otel-transformer/build.gradle
tools/sar/build.gradle

- Contribution 1 Have logback in unique version specified in `gradle.properties`
- Contribution 2 Have jersey in unique version specified in `gradle.properties`
..

Gh 7 Unique Jersey Version

---

gradle.properties

- Contribution 1 Update to AspectJ 1.9.23
..

Update to AspectJ 1.9.23 at runtime

---

analysis/build.gradle
common/test/kieker/java/EnumTest.java
common/test/kieker/test/common/util/dataformat/VariableLengthEncodingTest.java
tools/dar/build.gradle
tools/delta/build.gradle
tools/fxca/build.gradle
tools/log-replayer/build.gradle
tools/maa/build.gradle
tools/mop/build.gradle
tools/mop/test/kieker/tools/mop/merge/ModelRepositoryMergerTest.java
tools/restructuring/build.gradle
tools/runtime-analysis/build.gradle
tools/sar/build.gradle

- Merged JUnit 5 updates and fixes for tests

GH-15 JUnit 5.13.1
