bin/dev/release-check-short.sh
As SnapCI resolved the issue of the appearing non-executable shell-script file, the workaround is no longer needed and therefor removed.
=> KIEKER-1519 removed workaround for SnapCI

kieker-common/src/kieker/common/configuration/Configuration.java, kieker-monitoring/src-resources/META-INF/kieker.monitoring.default.properties, kieker-monitoring/src/kieker/monitoring/writer/filesystem/AsciiFileWriter.java, kieker-monitoring/src/kieker/monitoring/writer/filesystem/BinaryFileWriter.java, kieker-monitoring/test/kieker/monitoring/writer/filesystem/AsciiFileWriterTest.java, kieker-monitoring/test/kieker/monitoring/writer/filesystem/BinaryFileWriterTest.java
KIEKER-1521 fixed;
removed obsolete writer configuration options in kieker.monitoring.default.properties;
Added also tests for correct and incorrect config path values.
=> KIEKER-1521 fixed

gradle.properties
Due to the reduced number of static analysis errors and warnings, the corresponding thresholds have been lowered.
=> Reduced the thresholds for the static analysis tools

kieker-common/model/records/flow/Flow.irl, kieker-common/src-gen/kieker/common/record/database/AfterDatabaseEvent.java, kieker-common/src-gen/kieker/common/record/database/AfterDatabaseEventFactory.java, kieker-common/src-gen/kieker/common/record/database/BeforeDatabaseEvent.java, kieker-common/src-gen/kieker/common/record/database/BeforeDatabaseEventFactory.java, kieker-common/src-gen/kieker/common/record/database/DatabaseFailedEvent.java, kieker-common/src-gen/kieker/common/record/database/DatabaseFailedEventFactory.java, kieker-common/src-gen/kieker/common/record/flow/ICallObjectRecord.java, kieker-common/src-gen/kieker/common/record/flow/ICallRecord.java, kieker-common/src-gen/kieker/common/record/flow/IClassSignature.java, kieker-common/src-gen/kieker/common/record/flow/IEventRecord.java, kieker-common/src-gen/kieker/common/record/flow/IExceptionRecord.java, kieker-common/src-gen/kieker/common/record/flow/IInterfaceRecord.java, kieker-common/src-gen/kieker/common/record/flow/IObjectRecord.java, kieker-common/src-gen/kieker/common/record/flow/IOperationSignature.java, kieker-common/src-gen/kieker/common/record/flow/IThreadBasedRecord.java, kieker-common/src-gen/kieker/common/record/flow/ITraceRecord.java, kieker-common/src-gen/kieker/common/record/flow/trace/AbstractTraceEvent.java, kieker-common/src-gen/kieker/common/record/flow/trace/BeforeReceivedRemoteEvent.java, kieker-common/src-gen/kieker/common/record/flow/trace/BeforeReceivedRemoteEventFactory.java, kieker-common/src-gen/kieker/common/record/flow/trace/BeforeSentRemoteEvent.java, kieker-common/src-gen/kieker/common/record/flow/trace/BeforeSentRemoteEventFactory.java, kieker-common/src-gen/kieker/common/record/misc/HostApplicationMetaData.java, kieker-monitoring/src/kieker/monitoring/writer/explorviz/ExplorVizTcpWriter.java
A minor fix in the TemplateGenerator which produces in Java interfaces made it necessary to regenerated some interfaces. The generator fix was necessary, as the new changeable fields feature was only supported by the EventGenerator which can cause issues when implementing record rewriting stages.
=> code regeneration after TemplateGenerator (interfaces) fix.

Jenkinsfile
- Fixed wrong agent label name in "push to stable" stage.
=> KIEKER-1548: Fixed wrongly named label for agent.

Jenkinsfile
- Removed insertion of user ID to the 'docker run' command as Jenkins seems to do it now.
=> KIEKER-1779: Remove custom insertion of user IDs for docker execution.

config/pmdrules.xml, kieker-common/gradle.properties, kieker-monitoring/gradle.properties, kieker-tools/gradle.properties, kieker-tools/kdb/gradle.properties, kieker-tools/log-replayer/gradle.properties, kieker-tools/opad/gradle.properties
- Disabled chw's custom PMD rule " UnitTestMayNotExtendAnything"
- Reduced thresholds (i.e. set PMD error counters to 0)
=> Kieker 1787 disable chw test inheritance rule

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
- Bugfix: <init> was not allowed as methodName for PatternParser, therefore adaptive monitoring was not able to include/exclude constructors directly. This works now.
..
=> Allow Adaptive Monitoring for Constructor

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
- While new package.Class() will not match any signature, it is currently allowed. new package.Class<init>() would possibly match signatures. This PR adds a check that new is always used together with <init>.
..
=> Check constructor name for adaptive monitoring

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
- As return type, only Java identifiers are allowed, therefore, array-return types are not allowed. This commit fixes this by only parsing the identifier before the first [.
- This commit adds a simple test for this problem. 
..
=> Fix error: Parsing of Array-return-types was not possible

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
- In the current implementation, $ is just ignored by the PatternParser. Calls to inner classes contain $ in their signature and should therefore be allowed. Since regular expressions take $ as sign for the end of the regex, it needs to be escaped in order to make it usable in a pattern. Unfortunately, escaping this by the user is not possible, since \ is no allowed Java-identifier-part. Therefore, this commit always escapes $ signs.
- The commit tests that calls to methods of inner classes can be identified by the pattern.
..
=> Allow $ in pattern in order to make inner classes adaptive monitorable

kieker-analysis/src/kieker/analysis/source/file/DirectoryReaderStage.java
- Switched the DirectoryReaderStage from a plain AbstractConsumerStage to a AbstractTransformation to support Fluid interface.
=> Changed directory reader stage to AbstractTransformation.

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
Currently, if an instrumented run is executed, constructor signatures are `public new package.Class.<init>()`. If I create a pattern from this signature, it does not match the signature itself - it is only matched by the pattern created from `public package.Class.<init>()`. To make this work, I'd suggest to add `(new\\s)?` to the pattern if `new` is passed as return type.
..
=> new should be included as part of constructor signature

kieker-monitoring/src/kieker/monitoring/core/controller/WriterController.java
Unfortunately, the parameter for the Put-strategy to the queue specified the Take strategy and the Take-Parameter was used for the Put-strategy. This patch fixes this problem.
..
=> Correct strategy order

kieker-monitoring/test/kieker/monitoring/core/controller/tcp/SingleSocketRecordReaderTest.java
In Java 11 and 15, the unit tests fail because Powermock tries to instrument Javas internal classes. They should be ignored by Powermock (as described in https://github.com/mockito/mockito/issues/1562).
- Contribution 1 Add `@PowerMockIgnore
=> Powermock should not instrument Javas internal classes

kieker-analysis/src/kieker/analysis/source/file/DirectoryReaderStage.java
- Contribution 1 Use try with resources in DirectoryReaderStage
..
=> Use try-with-resources to asure that streams are closed in DirectoryReaderStage

kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java
- Contribution 1 Let pattern "public * Class.method()" also accept "public A.B.C Class.method()"
- Contribution 2 Test for this behaviour
..
=> Let * accept all types, including type names with packages

kieker-monitoring/src-resources/META-INF/kieker.monitoring.default.properties
- Contribution 1 The documentation stated that the offset of SystemNanoTimer is in milliseconds, but it is in the given timeunit. This is fixed in the documentation
..
=> Fix documentation for SystemNanoTimer's offset time unit

build.gradle
- Contribution 1 Create regular maven repo jar instead of uberjar for mainJar
..
=> Create usable library mainJar and only create uberJar for aspectJ

kieker-monitoring/integrationTest/kieker/monitoring/probe/aspectj/operationExecution/TestOperationExecutionInstrumentation.java, kieker-monitoring/src/kieker/monitoring/probe/aspectj/operationExecution/AbstractOperationExecutionAspect.java, kieker-monitoring/test-resources/example-projects-aspectj/example-operationexecutionrecord/src/test/java/net/example/Instrumentable.java
- Contribution 1 Static methods lead to `EmptyStackException` when instrumenting with `AbstractOperationExecutionAspect`. This is fixed by correctly handling the start of an operation exection.
..
=> Fix handling of static methods for OperationExecution instrumentation

kieker-documentation/instrumenting-software/Adaptive-Monitoring.rst, kieker-monitoring/gradle.properties, kieker-monitoring/src/kieker/monitoring/core/signaturePattern/PatternParser.java, kieker-monitoring/test/kieker/test/monitoring/junit/core/signaturePattern/TestPatternParser.java, kieker-monitoring/test/kieker/test/monitoring/util/signaturePattern/SignatureConstructor.java
- Extend PatternParser to handle 'default' modifier
- PMD warning threshold of kieker-monitoring module needed to be raised from 185 to 189, because
1. new method 'onSevenModifiers' introduces same warnings as existing methods 'onSixModifiers', 'onFiveModifiers', ...
2. Although making only small changes, class 'SignatureConstructor' is a possible god class now
=> Kieker 1913 Extend PatternParser to handle 'default' modifier

build.gradle, gradle/wrapper/gradle-wrapper.properties, kieker-examples/build.gradle, kieker-examples/monitoring/adaptive-monitoring/build.gradle, kieker-examples/monitoring/custom-timesource/build.gradle, kieker-examples/monitoring/probe-aspectj/build.gradle, kieker-examples/monitoring/probe-manual/build.gradle, kieker-examples/monitoring/probe-spring/build.gradle, kieker-examples/monitoring/sampler-jvm/build.gradle
As discussed, I completed the changes from the meetings. Now, the build works (at least for me) locally. It was not necessary to remove `cleanStandaloneExamples` as default task. Could you check whether this works for you?
- Contribution 1 Fix `./gradlew -x test -x check clean distribute`: Remove `clean.dependsOn cleanStandaloneExamples`
- Contribution 2 Remove `prepareExamplesForDistribution` task
- Contribution 3 Remove implementation dependency from example `build.gradle`, since the dependency from `lib` should be used
..
=> Kieker 1917 Fix Examples in Distribution Run

build.gradle
Currently, all PRs and MooBench are failing since the AspectJ classes are not included in the AspectJ jar. This is caused by the fact that there are `mainSubprojects`, but these do not contain `:monitoring:aspectj` (which makes sense, since AspectJ provide one set of probes for a `-javaagent` jar, but I wouldn't consider it a main subproject). 
To fix this, I've created aspectJSubprojects, that include `:monitoring:aspectj' and the required dependencies, but nothing else. For some time, the aspectj jar contained *everything*, including analysis etc. - this problem is fixed by this PR as well.
However, this is not really an ideal solutions, since:
- We duplicate the dependency configuration of the AspectJ probe jar (the `:monitoring:aspectj` module itself already specifies the dependencies …
=> Fix AspectJJar - include :monitoring:aspectj also 

bin/dev/release-check-extended.sh
- Contribution 1 Remove the function `run_gradle`, that is never used in the script (and documented that it runs ant...)
..
=> Remove unused function in release-check-extended.sh

examples/monitoring/probe-aspectj/build.gradle, monitoring/aspectj/build.gradle, monitoring/bytebuddy/build.gradle, monitoring/core/build.gradle
- Contribution 1 Release check extended currently fails due to an unnecessary dependency. This PR removes it
- Contribution 2 Additionally, unused gradle methods are removed.
..
=> Kieker 1986 kieker release check build fails

build.gradle, monitoring/bytebuddy/build.gradle, monitoring/core/build.gradle
This PR should supersede https://github.com/kieker-monitoring/kieker/pull/587. We shouldn't have a bunch of PRs, all containing the gradlew update, and being blocked by it - instead, I'll create the changes in new PRs and one PR for the Gradle update (and than we can debug the BuildScript-jacoco-problem there). 
- Contribution 1 Update ByteBuddy to 1.14.18
- Contribution 2 Update Jersey to 12.0.11
..
=> Kieker 1987 update only libs

tools/otel-transformer/build.gradle, tools/sar/build.gradle
- Fixing unstable build
TL;DR: logback packages (logback-core, logback-classic, logback-access) have to be updated all together.
From my tests, unstable build started to appear from [commit ``c1a70ed``](https://github.com/kieker-monitoring/kieker/commit/c1a70edd91b5b7e81b3ed90fba8f6a6c794ceecf), which updates logback-core from 1.5.12 to 1.5.15.
In detail, we had logback-classic 1.5.12 that requires ``ch/qos/logback/core/boolex/JaninoEventEvaluatorBase``, which is already [removed in logback-core 1.5.15](https://github.com/qos-ch/logback/commit/2cb6d520df7592ef1c3a198f1b5df3c10c93e183).
```
Executed test testCaseInsensitive() [kieker.tools.sar.signature.processor.MapBasedSignatureProcessorTest] with result: FAILURE …
```
=> Gh 5 fix jacoco

Jenkinsfile, analysis/build.gradle, build.gradle, common/build.gradle, examples/analysis/trace-analysis/build.gradle, examples/monitoring/adaptive-monitoring/build.gradle, examples/monitoring/custom-timesource/build.gradle, examples/monitoring/probe-aspectj/build.gradle, examples/monitoring/probe-manual-tcp/build.gradle, examples/monitoring/probe-manual/build.gradle, examples/monitoring/probe-spring/build.gradle, examples/monitoring/sampler-jvm/build.gradle, extension-cassandra/build.gradle, extension-kafka/build.gradle, model/build.gradle, monitoring/aspectj/build.gradle, monitoring/core/build.gradle, monitoring/disl/build.gradle, monitoring/spring/build.gradle, tools/build.gradle, tools/fxca/build.gradle
This pull request replaces the old OSSRH token with the new Central Portal Token.
- Since we are using the Staging API, we need the curl POST commandline for publication (not for SNAPSHOT uploads). See [Line 328 of Jenkinsfile](https://github.com/kieker-monitoring/kieker/blob/41f7071c2f49db375e475285cb9239cd4db2785a/Jenkinsfile#L328)
=> Migrate to OSSRH staging API
